/*
 * generated by Xtext
 */
package fil.emn.watij;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class WatijRuntimeModule extends fil.emn.watij.AbstractWatijRuntimeModule {

}
