/*
 * generated by Xtext
 */
package fil.emn.watij.ui.contentassist

import fil.emn.watij.ui.contentassist.AbstractWatijProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class WatijProposalProvider extends AbstractWatijProposalProvider {
}
