/*
 * generated by Xtext
 */
package fil.emn.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class WatijUiModule extends fil.emn.ui.AbstractWatijUiModule {
	public WatijUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
