/*
 * generated by Xtext
 */
package fil.emn;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class WatijRuntimeModule extends fil.emn.AbstractWatijRuntimeModule {

}
